config/routes.rb
Charon::Application.routes.draw do
  resources :activity_accounts, :except => [ :index, :new, :create ]
  resources :activity_reports, :except => [ :new, :create ]
  resources :addresses, :except => [ :index, :new, :create ]
  resources :agreements do
    resources :approvals, :only => [ :create, :index, :new ]
    resources :fulfillments, :only => [ :index ]
  end
  resources :approvals, :only => [ :show, :destroy ]
  resources :categories
  resources :documents, :only => [ :show ] do
    member do
      get :original
    end
  end
  resources :document_types
  resources :frameworks
  resources :fund_grants, :except => [ :create, :new, :index ] do
    resources :activity_accounts, :only => [ :index, :new, :create ]
    resources :fund_requests, :only => [ :create, :new, :index ]
  end
  resources :fund_editions, :only => [ :destroy ]
  resources :fund_items, :only => [ :destroy ]
  resources :fund_queues, :only => [ :show ] do
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :duplicate, :reviews_report
      end
    end
  end
  resources :fund_request_types
  resources :fund_requests, :except => [ :create, :new ] do
    member do
      get :reject, :documents_report
      put :do_reject, :submit, :withdraw, :reconsider
    end
    resources :approvals, :only => [ :create, :destroy, :index, :new ]
    resources :fund_items, :except => [ :destroy ]
  end
  resources :fund_sources, :except => [ :create, :new ] do
    resources :fund_grants, :only => [ :index ] do
      collection do
        get :released_report
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :unqueued
      end
    end
    resources :fund_tier_assignments, :only => [ :index, :new, :create ]
    resources :organizations, :only => [] do
      collection do
        get :untiered
      end
    end
  end
  resources :fund_tier_assignments, :only => [ :update, :destroy ]
  resources :inventory_items, :except => [ :new, :create ] do
      collection do
        get :retired, :active
      end
  end
  resources :local_event_expenses, :only => [ :index ]
  resources :memberships, :except => [ :create, :new ]
  resources :nodes, :except => [ :index, :create, :new ]
  resources :organizations do
    member do
      get :dashboard
    end
    resources :activity_accounts, :only => [ :index ]
    resources :activity_reports, :only => [ :index, :new, :create ] do
      collection do
        get :past, :current, :future
      end
    end
    resources :fulfillments, :only => [ :index ]
    resources :fund_grants, :only => [ :create, :new, :index ] do
      collection do
        get :closed, :open
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :active, :duplicate, :inactive
      end
    end
    resources :fund_sources, :only => [ :create, :new, :index ]
    resources :inventory_items, :only => [ :index, :new, :create ] do
      collection do
        get :retired, :active
      end
    end
    resources :memberships, :only => [ :create, :new, :index ] do
      collection do
        get :active
      end
    end
    resources :registrations, :only => [ :index ]
    resources :university_accounts, :only => [ :new, :create, :index ]
  end
  resources :registration_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :registrations, :only => [ :index, :show ] do
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
    resources :organizations, :only => [ :new, :create ]
  end
  resources :registration_terms do
    resources :registrations, :only => [ :index, :show ]
  end
  resources :roles
  resources :structures do
    resources :nodes, :only => [ :index, :create, :new ]
  end
  resources :university_accounts, :except => [ :new, :create ] do
    collection do
      get :activate
      put :do_activate
    end
  end
  resources :user_status_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :users do
    collection do
      get :admin, :staff
    end
    resources :addresses, :only => [ :index, :new, :create ]
    resources :approvals, :only => [ :index ]
    resources :fulfillments, :only => [ :index ]
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
  end

  resource :user_session

  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'profile', :to => 'users#profile', :as => 'profile'

  root :to => 'users#profile'
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  include UserNameLookup
  include OrganizationNameLookup

  attr_accessible :role_id, :active, :user_name, :organization_name
  attr_readonly :registration_id, :member_source_id

  scope :ordered, joins { [ organization, user ] }.
    order { [ organizations.last_name, organizations.first_name,
    users.last_name, users.first_name, users.net_id ] }
  scope :active, where( active: true )
  scope :inactive, where { active.not_eq( true ) }
  scope :requestor, lambda {
    active.where { role_id.in( Role.requestor.select { id } ) }
  }
  scope :reviewer, lambda {
    active.where { role_id.in( Role.reviewer.select { id } ) }
  }
  scope :manager, lambda {
    active.where { role_id.in( Role.manager.select { id } ) }
  }
  scope :fulfill_single_role, lambda { |framework|
    return scoped unless framework.requirements.select(&:role_id).any?
    where { |m|
      m.role_id.not_in( framework.requirements.single_role.scoped.select { role_id } ) |
      framework.requirement_roles.map { |role|
        m.role_id.eq( role.id ) &
        framework.requirements.single_role.select { |r| r.role_id == role.id }.
        map { |requirement| requirement.fulfillment_criterion m }.inject(:&)
      }.inject(:|)
    }
  }
  scope :fulfill_all_role, lambda { |framework|
    return scoped unless framework.requirements.reject(&:role_id).any?
    where { |m|
        framework.requirements.all_roles.
        map { |requirement| requirement.fulfillment_criterion m }.inject(:&)
    }
  }
  # Find all memberships which fulfill a framework
  # * not subject to role-specified or meets all role-specified
  # * meets all organizational
  scope :fulfill, lambda { |framework|
    fulfill_single_role( framework ).fulfill_all_role( framework )
  }
  scope :approver_for, lambda { |framework|
    where( role_id: framework.approvers.scoped.select { role_id } )
  }
  scope :unfulfilled_for, lambda { |framework|
    where { |m| m.id.not_in( framework.memberships.scoped.select { id } ) }
  }

  belongs_to :user, inverse_of: :memberships
  belongs_to :role, inverse_of: :memberships
  belongs_to :registration, inverse_of: :memberships
  belongs_to :organization, inverse_of: :memberships
  belongs_to :member_source, inverse_of: :memberships
  has_and_belongs_to_many :frameworks

  before_validation :set_organization_from_registration, :set_from_member_source
  after_save :update_frameworks

  validates :user, presence: true
  validates :role, presence: true
  validate :must_have_registration_or_organization

  def update_frameworks
    return true if Framework.skip_update_frameworks
    self.frameworks.clear unless active?
    self.frameworks = Framework.fulfilled_by( self )
  end

  def set_organization_from_registration
    if registration
      self.active = registration.current?
      self.organization = registration.organization if registration.organization
    end
    true
  end

  def set_from_member_source
    if member_source
      self.role = member_source.role
      self.organization = member_source.organization
    end
  end

  def must_have_registration_or_organization
    errors.add( :base, 'Must have a registration or organization.' ) unless (registration || organization)
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_filter :require_user
  before_filter :initialize_context
  before_filter :initialize_index, :only => [ :index, :active ]
  before_filter :new_membership_from_params, :only => [ :new, :create ]
  filter_access_to :new, :create, :edit, :update, :destroy, :show, :attribute_check => true
  filter_access_to :index, :active do
    permitted_to! :show, @organization if @organization
    permitted_to! :show, @user if @user
    permitted_to! :show, @registration if @registration
    true
  end

  # GET /organizations/:organization_id/memberships/active
  # GET /organizations/:organization_id/memberships/active.xml
  def active
    if @context
      add_breadcrumb 'Active', polymorphic_path( [ :active, @context, :memberships ] )
    end
    @memberships = @memberships.active
    index
  end

  # GET /organizations/:organization_id/memberships
  # GET /organizations/:organization_id/memberships.xml
  def index
    @search = @memberships.search( params[:search] )
    @memberships = @search.result.page(params[:page])

    respond_to do |format|
      format.html { render :action => 'index' } # index.html.erb
      format.xml  { render :xml => @memberships }
    end
  end

  # GET /memberships/1
  # GET /memberships/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /organizations/:organization_id/memberships/new
  # GET /organizations/:organization_id/memberships/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @membership }
    end
  end

  # GET /memberships/1/edit
  def edit
    # edit.html.erb
  end

  # POST /organizations/:organization_id/memberships
  # POST /organizations/:organization_id/memberships.xml
  def create
    respond_to do |format|
      if @membership.save
        flash[:notice] = 'Membership was successfully created.'
        format.html { redirect_to(@membership) }
        format.xml  { render :xml => @membership, :status => :created, :location => @membership }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /memberships/1
  # PUT /memberships/1.xml
  def update
    respond_to do |format|
      if @membership.update_attributes(params[:membership])
        flash[:notice] = 'Membership was successfully updated.'
        format.html { redirect_to(@membership) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @membership.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.xml
  def destroy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to user_memberships_url @membership.user }
      format.xml  { head :ok }
    end
  end

  private

  def initialize_context
    @membership = Membership.find params[:id] if params[:id]
    @context = Organization.find params[:organization_id] if params[:organization_id]
    @context = User.find params[:user_id] if params[:user_id]
    @context = Registration.find params[:registration_id] if params[:registration_id]
    if @context
      add_breadcrumb @context, url_for( @context )
      add_breadcrumb 'Memberships', polymorphic_path( [ @context, :memberships ] )
    end
  end

  def initialize_index
    @memberships = Membership.scoped
    if @context
      @memberships = @memberships.scoped( :conditions => { :organization_id => @context.id } ) if @context.class == Organization
      @memberships = @memberships.scoped( :conditions => { :user_id => @context.id } ) if @context.class == User
      @memberships = @memberships.scoped( :conditions => { :registration_id => @context.id } ) if @context.class == Registration
    end
  end

  def new_membership_from_params
    @membership = @context.memberships.build( params[:membership] ) if @context
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<% organization ||= false -%>
<% user ||= false -%>
  <%= render "shared/error_messages", :target => form.object %>
  <%= form.inputs do %>
    <% if form.object.new_record? %>
      <% unless organization %>
        <%= form.input :organization_name, :label => 'Organization' %>
      <% end %>
      <% unless user %>
        <%= form.input :user_name, :label => 'User' %>
      <% end %>
    <% end %>
    <%= form.input :active, :label => "Active?", :as => :radio %>
    <%= form.input :role %>
  <% end %>
  <%= form.actions %>

app/views/memberships/_membership.html.erb
<% organization ||= false %>
<% user ||= false %>
<% if permitted_to? :show, membership -%>
  <%= table_row_tag do %>
    <% unless organization -%>
    <td><%= membership.organization %></td>
    <% end -%>
    <% unless user -%>
    <td><%= membership.user.name %></td>
    <td><%= membership.user.net_id %></td>
    <% end -%>
    <td><%= membership.registration_id? ? 'Yes' : 'No' %></td>
    <td><%= membership.role %></td>
    <td><%= link_to 'Show', membership %></td>
    <td><%= link_to( 'Edit', edit_membership_path(membership) ) if permitted_to?( :edit, membership ) %></td>
    <td><%= link_to( 'Destroy', membership, data: { confirm: 'Are you sure?' },
      method: :delete ) if permitted_to?( :destroy, membership ) %></td>
  <% end %>
<% end -%>

app/views/memberships/_memberships.html.erb
<% organization ||= false -%>
<% user ||= false -%>
<table>
<thead>
  <tr>
    <% unless organization %>
    <th>Organization</th>
    <% end %>
    <% unless user %>
    <th>User name</th>
    <th>User net id</th>
    <% end %>
    <th>Registration?</th>
    <th>Role</th>
  </tr>
</thead>
<tbody>
<%= render :partial => "memberships/membership", :collection => memberships,
  :locals => { :organization => organization, :user => user } %>
</tbody>
</table>

app/views/memberships/edit.html.erb
<h2>Editing membership</h2>

<%= semantic_form_for(@membership) do |f| %>
  <%= render :partial => 'form', :object => f %>
<% end %>

<p>
<%= link_to 'Show', @membership %> |
<%= link_to "Back to #{@membership.user} memberships", user_memberships_path( @membership.user ) %>
<% if @membership.organization -%>
 | <%= link_to "Back to #{@membership.organization} memberships", organization_memberships_path( @membership.organization ) %>
<% end -%>
</p>

app/views/memberships/index.html.erb
<h2>Listing memberships for <%= @context %></h2>

<%= paginate @memberships %>

<%= render :partial => "memberships", :object => @memberships, :locals => {
  :organization => @context.class == Organization, :user => @context.class == User
} %>

<%= paginate @memberships %>

<br />

<p>
<% if @context && permitted_to?( :create, @context.memberships.build ) %>
  <%= link_to "New membership for #{@context}", new_polymorphic_path( [ @context, :membership ] ) %>
<% end %>
</p>

app/views/memberships/new.html.erb
<h2>New membership</h2>

<%= semantic_form_for( @membership, :url => polymorphic_path( [ @context, :memberships ] ) ) do |f| %>
  <%= render :partial => 'form', :object => f, :locals => { :organization => @context.class == Organization,
    :user => @context.class == User } %>
<% end %>

<p>
<%= link_to "Back to #{@context}", polymorphic_path( [ @context, :memberships ] ) %>
</p>

app/views/memberships/show.html.erb
<p>
  <b>Organization:</b> <%=h @membership.organization %>
</p>

<p>
  <b>User:</b> <%=h @membership.user %>
</p>

<p>
  <b>Registration:</b> <%=h @membership.registration %>
</p>

<p>
  <b>Active?</b> <%= @membership.active? ? 'Yes' : 'No' %>
</p>

<p>
  <b>Role:</b> <%=h @membership.role %>
</p>

<h3>Authorized frameworks</h3>

<p>
This membership has access in the following framework contexts:
</p>

<% if @membership.frameworks.any? %>
<ul>
<% @membership.frameworks.each do |framework| %>
<li><%= framework %></li>
<% end %>
</ul>
<% else %>
<p>No frameworks.</p>
<% end %>


<p>
<%= link_to( 'Edit', edit_membership_path(@membership) ) if permitted_to? :edit, @membership %> |
<%= link_to "Back to #{@membership.user} memberships", polymorphic_path( [ @membership.user, :memberships ] ) %>
<% if @membership.organization -%>
 | <%= link_to "Back to #{@membership.organization} memberships", polymorphic_path( [ @membership.organization, :memberships ] ) %>
<% end -%>
<% if @membership.registration -%>
 | <%= link_to "Back to #{@membership.registration} memberships", polymorphic_path( [ @membership.registration, :memberships ] ) %>
<% end -%>
</p>