config/routes.rb
Charon::Application.routes.draw do
  resources :activity_accounts, :except => [ :index, :new, :create ]
  resources :activity_reports, :except => [ :new, :create ]
  resources :addresses, :except => [ :index, :new, :create ]
  resources :agreements do
    resources :approvals, :only => [ :create, :index, :new ]
    resources :fulfillments, :only => [ :index ]
  end
  resources :approvals, :only => [ :show, :destroy ]
  resources :categories
  resources :documents, :only => [ :show ] do
    member do
      get :original
    end
  end
  resources :document_types
  resources :frameworks
  resources :fund_grants, :except => [ :create, :new, :index ] do
    resources :activity_accounts, :only => [ :index, :new, :create ]
    resources :fund_requests, :only => [ :create, :new, :index ]
  end
  resources :fund_editions, :only => [ :destroy ]
  resources :fund_items, :only => [ :destroy ]
  resources :fund_queues, :only => [ :show ] do
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :duplicate, :reviews_report
      end
    end
  end
  resources :fund_request_types
  resources :fund_requests, :except => [ :create, :new ] do
    member do
      get :reject, :documents_report
      put :do_reject, :submit, :withdraw, :reconsider
    end
    resources :approvals, :only => [ :create, :destroy, :index, :new ]
    resources :fund_items, :except => [ :destroy ]
  end
  resources :fund_sources, :except => [ :create, :new ] do
    resources :fund_grants, :only => [ :index ] do
      collection do
        get :released_report
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :unqueued
      end
    end
    resources :fund_tier_assignments, :only => [ :index, :new, :create ]
    resources :organizations, :only => [] do
      collection do
        get :untiered
      end
    end
  end
  resources :fund_tier_assignments, :only => [ :update, :destroy ]
  resources :inventory_items, :except => [ :new, :create ] do
      collection do
        get :retired, :active
      end
  end
  resources :local_event_expenses, :only => [ :index ]
  resources :memberships, :except => [ :create, :new ]
  resources :nodes, :except => [ :index, :create, :new ]
  resources :organizations do
    member do
      get :dashboard
    end
    resources :activity_accounts, :only => [ :index ]
    resources :activity_reports, :only => [ :index, :new, :create ] do
      collection do
        get :past, :current, :future
      end
    end
    resources :fulfillments, :only => [ :index ]
    resources :fund_grants, :only => [ :create, :new, :index ] do
      collection do
        get :closed, :open
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :active, :duplicate, :inactive
      end
    end
    resources :fund_sources, :only => [ :create, :new, :index ]
    resources :inventory_items, :only => [ :index, :new, :create ] do
      collection do
        get :retired, :active
      end
    end
    resources :memberships, :only => [ :create, :new, :index ] do
      collection do
        get :active
      end
    end
    resources :registrations, :only => [ :index ]
    resources :university_accounts, :only => [ :new, :create, :index ]
  end
  resources :registration_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :registrations, :only => [ :index, :show ] do
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
    resources :organizations, :only => [ :new, :create ]
  end
  resources :registration_terms do
    resources :registrations, :only => [ :index, :show ]
  end
  resources :roles
  resources :structures do
    resources :nodes, :only => [ :index, :create, :new ]
  end
  resources :university_accounts, :except => [ :new, :create ] do
    collection do
      get :activate
      put :do_activate
    end
  end
  resources :user_status_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :users do
    collection do
      get :admin, :staff
    end
    resources :addresses, :only => [ :index, :new, :create ]
    resources :approvals, :only => [ :index ]
    resources :fulfillments, :only => [ :index ]
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
  end

  resource :user_session

  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'profile', :to => 'users#profile', :as => 'profile'

  root :to => 'users#profile'
end

app/models/activity_report.rb
class ActivityReport < ActiveRecord::Base
  SEARCHABLE = [ :organization_name_contains, :description_contains ]

  attr_accessible :number_of_others, :number_of_undergrads, :number_of_grads,
    :description, :starts_on, :ends_on
  attr_readonly :organization_id

  belongs_to :organization, inverse_of: :activity_reports

  scope :ordered, includes { organization }.
    order( 'organizations.last_name ASC, organizations.first_name ASC, ' +
      'activity_reports.starts_on ASC, activity_reports.description ASC' )
  scope :past, lambda { where 'activity_reports.ends_on < ?', Time.zone.today }
  scope :current, lambda { where(
    'activity_reports.starts_on <= :date AND activity_reports.ends_on >= :date',
    :date => Time.zone.today ) }
  scope :future, lambda { where 'activity_reports.starts_on > ?', Time.zone.today }
  scope :organization_name_contains, lambda { |name|
    where( 'organizations.last_name LIKE :n OR organizations.first_name LIKE :n',
      :n => "%#{name}%" )
  }
  scope :description_contains, lambda { |content|
    where { |activity_reports| activity_reports.description =~ "%#{content}%" }
  }

  has_paper_trail class_name: 'SecureVersion'

  validates :organization, presence: true
  validates :description, presence: true
  validates :number_of_others, numericality: { integer_only: true,
    greater_than_or_equal_to: 0 }
  validates :number_of_undergrads, numericality: { integer_only: true,
    greater_than_or_equal_to: 0 }
  validates :number_of_grads, numericality: { integer_only: true,
    greater_than_or_equal_to: 0 }
  validates :starts_on, timeliness: { type: :date }
  validates :ends_on, timeliness: { type: :date,
    on_or_after: :starts_on }
end

app/controllers/activity_reports_controller.rb
class ActivityReportsController < ApplicationController
  before_filter :require_user
  before_filter :initialize_context
  before_filter :initialize_index, :only => [ :index, :past, :current, :future ]
  before_filter :new_activity_report_from_params, :only => [ :new, :create ]
  filter_access_to :new, :create, :edit, :update, :destroy, :show, :attribute_check => true
  filter_access_to :index, :past, :current, :future do
    permitted_to!( :show, @organization ) if @organization
    permitted_to!( :index )
  end

  def past
    @activity_reports = @activity_reports.past
    index
  end

  def current
    @activity_reports = @activity_reports.current
    index
  end

  def future
    @activity_reports = @activity_reports.future
    index
  end

  # GET /organizations/:organization_id/activity_reports
  # GET /organizations/:organization_id/activity_reports.xml
  def index
    @search = params[:search] || Hash.new
    @search.each do |k,v|
      if !v.blank? && ActivityReport::SEARCHABLE.include?( k.to_sym )
        @activity_reports = @activity_reports.send k, v
      end
    end
    @activity_reports = @activity_reports.page(params[:page])

    respond_to do |format|
      format.html { render :action => 'index' }
      format.csv { csv_index }
      format.xml  { render :xml => @activity_reports }
    end
  end

  # GET /activity_reports/1
  # GET /activity_reports/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity_report }
    end
  end

  # GET /organizations/:organization_id/activity_reports/new
  # GET /organizations/:organization_id/activity_reports/new.xml
  # TODO -- should this action exist?
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity_report }
    end
  end

  # POST /organizations/:organization_id/activity_reports
  # POST /organizations/:organization_id/activity_reports.xml
  def create
    respond_to do |format|
      if @activity_report.save
        flash[:notice] = 'Activity report was successfully created.'
        format.html { redirect_to @activity_report }
        format.xml  { render :xml => @activity_report, :status => :created, :location => @activity_report }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /activity_reports/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
    end
  end

  # PUT /activity_reports/1
  # PUT /activity_reports/1.xml
  def update
    respond_to do |format|
      if @activity_report.update_attributes(params[:activity_report])
        flash[:notice] = 'Activity report was successfully updated.'
        format.html { redirect_to @activity_report }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity_report.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_reports/1
  # DELETE /activity_reports/1.xml
  def destroy
    @activity_report.destroy

    respond_to do |format|
      flash[:notice] = 'Activity report was successfully destroyed.'
      format.html { redirect_to( profile_url ) }
      format.xml  { head :ok }
    end
  end

  private

  def initialize_context
    @activity_report = ActivityReport.find params[:id] if params[:id]
    @organization = Organization.find params[:organization_id] if params[:organization_id]
    @organization ||= @activity_report.organization if @activity_report
    @context ||= @organization
    add_breadcrumb @organization.name, organization_path( @organization ) if @organization
  end

  def initialize_index
    @activity_reports = ActivityReport.scoped
    @activity_reports = @activity_reports.where(:organization_id => @organization.id) if @organization
    @activity_reports = @activity_reports.with_permissions_to(:show).ordered.
      includes { organization.memberships.role }
  end

  def new_activity_report_from_params
    @activity_report = @organization.activity_reports.build( params[:activity_report] )
  end

  def csv_index
    csv_string = CSV.generate do |csv|
      csv << %w( organization description starts_on ends_on )
      @activity_reports.each do |activity_report|
        next unless permitted_to?( :review, activity_report )
        csv << [ activity_report.organization.name,
          activity_report.description,
          activity_report.starts_on.to_formatted_s( :rfc822 ),
          activity_report.ends_on.to_formatted_s( :rfc822 ) ]
      end
    end
    send_data csv_string, :disposition => "attachment; filename=activity_reports.csv"
  end

end

app/helpers/activity_reports_helper.rb
module ActivityReportsHelper
end

app/views/activity_reports/_activity_report.html.erb
<% organization ||= false -%>
<%= table_row_tag do %>
  <% unless organization %>
  <td><%= activity_report.organization %></td>
  <% end %>
  <td><%= activity_report.description %></td>
  <td><%= activity_report.starts_on.to_formatted_s :rfc822 %></td>
  <td><%= activity_report.ends_on.to_formatted_s :rfc822 %></td>
  <td><%= link_to 'Show', activity_report %></td>
  <td><%= link_to( 'Edit', [:edit, activity_report] ) if permitted_to? :edit, activity_report %></td>
  <td><%= link_to( 'Destroy', activity_report, data: { confirm: 'Are you sure?' },
    method: :delete) if permitted_to? :destroy, activity_report %></td>
<% end %>

app/views/activity_reports/_activity_reports.html.erb
<% organization ||= false %>

<table>
<thead>
  <tr>
  <% unless organization -%>
    <th>Organization</th>
  <% end -%>
    <th>Description</th>
    <th>Starts on</th>
    <th>Ends on</th>
  </tr>
</thead>
<tbody>
  <%= render :partial => 'activity_reports/activity_report',
    :collection => activity_reports, :locals => { :organization => organization } %>
</tbody>
</table>

app/views/activity_reports/_form.html.erb
<%= render "shared/error_messages", :target => form.object %>
<%= form.inputs do %>
  <%= form.input :description, :hint => 'Provide the title or a brief description of the activity' %>
  <%= form.input :starts_on, :as => :date_picker,
    :hint => 'The date of the activity or the first date if activity occurs over a period of time.' %>
  <%= form.input :ends_on, :as => :date_picker,
    :hint => 'The date of the activity or the last date if activity occurs over a period of time.' %>
  <%= form.input :number_of_undergrads %>
  <%= form.input :number_of_grads %>
  <%= form.input :number_of_others %>
<% end %>
<%= form.actions %>

app/views/activity_reports/edit.html.erb
<h2>Editing <%=h @activity_report %></h2>

<%= semantic_form_for( @activity_report ) do |f| %>
  <%= render :partial => 'form', :object => f %>
<% end %>

<p>
<%= link_to 'Show', @activity_report %> |
<%= link_to 'Back', organization_activity_reports_path( @activity_report.organization ) %>
</p>

app/views/activity_reports/index.html.erb
<h2>Listing activity reports</h2>

<%= form_tag polymorphic_path( [ @context, :activity_reports ] ), :method => :get do |f| %>
  <% unless @organization -%>
  <p>
    <%= label_tag 'search[organization_name_contains]', 'Organization' %>
    <%= search_field_tag 'search[organization_name_contains]', @search['fund_source_name_contains'] %>
  </p>
  <% end -%>
  <p>
    <%= label_tag 'search[description_contains]', 'Description' %>
    <%= search_field_tag 'search[description_contains]', @search['description_contains'] %>
  </p>
  <p>
    <%= submit_tag 'Search' %>
  </p>
<% end %>

<%= paginate @activity_reports %>

<hr/>

<%= render :partial => "activity_reports/activity_reports",
  :object => @activity_reports, :locals => { :organization => @organization } %>

<hr/>

<%= paginate @activity_reports %>

<hr/>

<p>
<% if @organization -%>
<%= link_to h("Back to #{@organization}"), @organization %> |
<% if permitted_to? :create, @organization.activity_reports.build %>
<%= link_to h("New activity report for #{@organization}"),
  new_organization_activity_report_path( @organization ) %>
<% end %>
<% end -%>
</p>

app/views/activity_reports/new.html.erb
<h2>New activity report for <%=h @activity_report.organization %></h2>

<%= semantic_form_for(@activity_report, :url => organization_activity_reports_path(@activity_report.organization) ) do |f| %>
  <%= render :partial => 'form', :object => f %>
<% end %>

app/views/activity_reports/show.html.erb
<h2>Activity report</h2>

<p><b>Description:</b> <%=h @activity_report.description %></p>

<p><b>Number of undergrads:</b> <%= @activity_report.number_of_undergrads %></p>

<p><b>Number of grads:</b> <%= @activity_report.number_of_grads %></p>

<p><b>Number of others:</b> <%= @activity_report.number_of_others %></p>

<p><b>Starts on:</b> <%= @activity_report.starts_on.to_formatted_s :long_ordinal %></p>

<p><b>Ends on:</b> <%= @activity_report.ends_on.to_formatted_s :long_ordinal %></p>

<p>
<%= link_to h("Back to #{@activity_report.organization}"), @activity_report.organization %> |
<%= link_to 'Edit', edit_activity_report_path(@activity_report) %>
</p>