config/routes.rb
Charon::Application.routes.draw do
  resources :activity_accounts, :except => [ :index, :new, :create ]
  resources :activity_reports, :except => [ :new, :create ]
  resources :addresses, :except => [ :index, :new, :create ]
  resources :agreements do
    resources :approvals, :only => [ :create, :index, :new ]
    resources :fulfillments, :only => [ :index ]
  end
  resources :approvals, :only => [ :show, :destroy ]
  resources :categories
  resources :documents, :only => [ :show ] do
    member do
      get :original
    end
  end
  resources :document_types
  resources :frameworks
  resources :fund_grants, :except => [ :create, :new, :index ] do
    resources :activity_accounts, :only => [ :index, :new, :create ]
    resources :fund_requests, :only => [ :create, :new, :index ]
  end
  resources :fund_editions, :only => [ :destroy ]
  resources :fund_items, :only => [ :destroy ]
  resources :fund_queues, :only => [ :show ] do
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :duplicate, :reviews_report
      end
    end
  end
  resources :fund_request_types
  resources :fund_requests, :except => [ :create, :new ] do
    member do
      get :reject, :documents_report
      put :do_reject, :submit, :withdraw, :reconsider
    end
    resources :approvals, :only => [ :create, :destroy, :index, :new ]
    resources :fund_items, :except => [ :destroy ]
  end
  resources :fund_sources, :except => [ :create, :new ] do
    resources :fund_grants, :only => [ :index ] do
      collection do
        get :released_report
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :unqueued
      end
    end
    resources :fund_tier_assignments, :only => [ :index, :new, :create ]
    resources :organizations, :only => [] do
      collection do
        get :untiered
      end
    end
  end
  resources :fund_tier_assignments, :only => [ :update, :destroy ]
  resources :inventory_items, :except => [ :new, :create ] do
      collection do
        get :retired, :active
      end
  end
  resources :local_event_expenses, :only => [ :index ]
  resources :memberships, :except => [ :create, :new ]
  resources :nodes, :except => [ :index, :create, :new ]
  resources :organizations do
    member do
      get :dashboard
    end
    resources :activity_accounts, :only => [ :index ]
    resources :activity_reports, :only => [ :index, :new, :create ] do
      collection do
        get :past, :current, :future
      end
    end
    resources :fulfillments, :only => [ :index ]
    resources :fund_grants, :only => [ :create, :new, :index ] do
      collection do
        get :closed, :open
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :active, :duplicate, :inactive
      end
    end
    resources :fund_sources, :only => [ :create, :new, :index ]
    resources :inventory_items, :only => [ :index, :new, :create ] do
      collection do
        get :retired, :active
      end
    end
    resources :memberships, :only => [ :create, :new, :index ] do
      collection do
        get :active
      end
    end
    resources :registrations, :only => [ :index ]
    resources :university_accounts, :only => [ :new, :create, :index ]
  end
  resources :registration_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :registrations, :only => [ :index, :show ] do
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
    resources :organizations, :only => [ :new, :create ]
  end
  resources :registration_terms do
    resources :registrations, :only => [ :index, :show ]
  end
  resources :roles
  resources :structures do
    resources :nodes, :only => [ :index, :create, :new ]
  end
  resources :university_accounts, :except => [ :new, :create ] do
    collection do
      get :activate
      put :do_activate
    end
  end
  resources :user_status_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :users do
    collection do
      get :admin, :staff
    end
    resources :addresses, :only => [ :index, :new, :create ]
    resources :approvals, :only => [ :index ]
    resources :fulfillments, :only => [ :index ]
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
  end

  resource :user_session

  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'profile', :to => 'users#profile', :as => 'profile'

  root :to => 'users#profile'
end

app/models/activity_account.rb
class ActivityAccount < ActiveRecord::Base
  attr_accessible :comments, :category_id
  attr_readonly :fund_grant_id

  belongs_to :fund_grant, inverse_of: :activity_accounts
  belongs_to :category, inverse_of: :activity_accounts

  has_many :adjustments, dependent: :destroy, class_name: 'AccountAdjustment',
    inverse_of: :activity_account
  has_many :allocations, through: :fund_grant, source: :fund_allocations,
    conditions: Proc.new {
      { fund_item_id: FundItem.with_category( category ) }
    }
  has_one :organization, through: :fund_grant
  has_one :fund_source, through: :fund_grant

  scope :organization_id_equals, lambda { |id|
    joins(:fund_grant).where { fund_grants.organization_id.eq( id ) }
  }
  scope :organization_id_in, lambda { |ids|
    joins(:fund_grant).where { fund_grants.organization_id.in( ids ) }
  }
  scope :transactable_for, lambda { |activity_account|
    organization_id_in( [ activity_account.organization.id,
      activity_account.fund_source.organization.id ] ).
    where { id.not_eq( activity_account.id ) }
  }
  scope :with_balances, select {
    sum_allocations_sql = FundAllocation.unscoped.joins { fund_item.node }.select { SUM(amount) }.
      where { fund_items.fund_grant_id.eq(activity_accounts.fund_grant_id) &
       nodes.category_id.eq(activity_accounts.category_id) }.to_sql
    sum_adjustments_sql = AccountAdjustment.unscoped.select { SUM(amount) }.
      where { activity_account_id.eq( activity_accounts.id ) }.to_sql
    [ `\`activity_accounts\`.*`,
      `IFNULL( (#{sum_allocations_sql}), 0.0 )`.as(sum_allocations),
      `IFNULL( (#{sum_adjustments_sql}), 0.0 )`.as(sum_adjustments) ]
  }
  scope :current, joins { fund_grant }.merge( FundGrant.unscoped.current )
  scope :closed, joins { fund_grant }.merge( FundGrant.unscoped.closed )

  validates :fund_grant, presence: true
  validates :category, presence: true
  validates :fund_grant_id, uniqueness: { scope: [ :category_id ] }

  # If sum of allocations is cached, use it.  Otherwise, calculate
  def sum_allocations
    attributes['sum_allocations'] ? attributes['sum_allocations'] : allocations.sum(:amount)
  end

  # If sum of adjustments is cached, use it.  Otherwise, calculate.
  def sum_adjustments
    attributes['sum_adjustments'] ? attributes['sum_adjustments'] : adjustments.sum(:amount)
  end

  # Total available funds for activity account is allocation plus manual adjustments
  def sum_available; sum_allocations + sum_adjustments; end

end

app/controllers/activity_accounts_controller.rb
class ActivityAccountsController < ApplicationController
  before_filter :require_user
  before_filter :initialize_context
  before_filter :initialize_index, :only => [ :index, :past, :current, :future ]
  before_filter :new_activity_account_from_params, :only => [ :new, :create ]
  filter_access_to :new, :create, :edit, :update, :destroy, :show, attribute_check: true
  filter_access_to :index do
    permitted_to!( :show, @context ) if @context
    true
  end

  # GET /activity_accounts
  # GET /activity_accounts.xml
  def index
    @search = @activity_accounts.search( params[:search] )
    @activity_accounts = @search.result.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @activity_accounts }
    end
  end

  # GET /activity_accounts/1
  # GET /activity_accounts/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @activity_account }
    end
  end

  # GET /activity_accounts/new
  # GET /activity_accounts/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity_account }
    end
  end

  # GET /activity_accounts/1/edit
  def edit; end

  # POST /activity_accounts
  # POST /activity_accounts.xml
  def create
    respond_to do |format|
      if @activity_account.save
        format.html { redirect_to(@activity_account, :notice => 'Activity account was successfully created.') }
        format.xml  { render :xml => @activity_account, :status => :created, :location => @activity_account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activity_accounts/1
  # PUT /activity_accounts/1.xml
  def update
    respond_to do |format|
      if @activity_account.update_attributes(params[:activity_account])
        format.html { redirect_to(@activity_account, :notice => 'Activity account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_accounts/1
  # DELETE /activity_accounts/1.xml
  def destroy
    @activity_account.destroy

    respond_to do |format|
      format.html { redirect_to fund_grant_activity_accounts_url( @activity_account.fund_grant ) }
      format.xml  { head :ok }
    end
  end

  private

  def initialize_context
    @activity_account = ActivityAccount.find( params[:id] ) if params[:id]
    @fund_grant = FundGrant.find( params[ :fund_grant_id ] ) if params[:fund_grant_id]
    @organization = Organization.find( params[:organization_id] ) if params[:organization_id]
    @context = @fund_grant || @organization
    add_breadcrumb @organization.name, organization_path( @organization ) if @organization
    add_breadcrumb @fund_grant, fund_grant_path( @fund_grant ) if @fund_grant
  end

  def initialize_index
    @activity_accounts = ActivityAccount.scoped
    @activity_accounts = @activity_accounts.organization_id_equals( @organization.id ) if @organization
    @activity_accounts = @activity_accounts.where(
      fund_grant_id: @fund_grant.id ) if @fund_grant
    @activity_accounts = @activity_accounts.with_permissions_to(:show).with_balances
  end

  def new_activity_account_from_params
    @activity_account = @fund_grant.activity_accounts.build( params[:activity_account] )
  end

end

app/helpers/activity_accounts_helper.rb
module ActivityAccountsHelper
end

app/views/activity_accounts/_activity_account.html.erb
<% organization ||= false %>
<% with_balances ||= false %>
  <%= table_row_tag do %>
    <% unless organization %>
    <td><%= activity_account.fund_grant.organization %></td>
    <% end %>
    <td><%= activity_account.fund_grant.fund_source %></td>
    <td><%= activity_account.category %></td>
    <% if with_balances %>
    <td><%=number_to_currency activity_account.sum_allocations %></td>
    <td><%=number_to_currency activity_account.sum_adjustments %></td>
    <td><%=number_to_currency activity_account.sum_available %></td>
    <% end %>
    <td><%= link_to 'Show', activity_account %></td>
    <td><%= link_to 'Edit', edit_activity_account_path(activity_account) if permitted_to? :edit, activity_account %></td>
    <td><%= link_to( 'Destroy', activity_account, data: { confirm: 'Are you sure?' },
      method: :delete ) if permitted_to? :destroy, activity_account %></td>
  <% end %>

app/views/activity_accounts/_activity_accounts.html.erb
<% organization ||= false %>
<% with_balances ||= false %>
<table id='activity-accounts'>
<thead>
  <tr>
    <% unless organization %>
    <th>Organization</th>
    <% end %>
    <th>Source</th>
    <th>Category</th>
    <% if with_balances %>
    <th>Allocations</th>
    <th>Adjustments</th>
    <th>Available</th>
    <% end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<%=render partial: "activity_accounts/activity_account", collection: activity_accounts,
  locals: { with_balances: with_balances, organization: organization } %>
</tbody>
</table>

app/views/activity_accounts/_form.html.erb
<%= form.inputs do %>
<%= form.input :category %>
<%= form.input :comments %>
<% end %>

<%= form.actions %>

app/views/activity_accounts/edit.html.erb
<h2>Editing activity account</h2>

<%= semantic_form_for(@activity_account) do |f| %>
  <% render :partial => 'activity_accounts/form', :object => f %>
<% end %>

<p>
<%= link_to 'Show', @activity_account %>
</p>

app/views/activity_accounts/index.html.erb
<h2>Listing activity accounts for <%= @context %></h2>

<%= paginate @activity_accounts %>

<%= render partial: "activity_accounts", object: @activity_accounts,
  locals: { organization: @organization, with_balances: true } %>

<%= paginate @activity_accounts %>

<br />

<p>
<% if @fund_grant && permitted_to?( :create, @fund_grant.activity_accounts.build ) %>
<%= link_to 'New activity account', new_fund_grant_activity_account_path( @fund_grant ) %>
<% end %>
</p>

app/views/activity_accounts/new.html.erb
<h2>New activity account</h2>

<%= semantic_form_for(@activity_account,
  :url => fund_grant_activity_accounts_path( @activity_account.fund_grant ) ) do |f| %>
  <% render :partial => 'activity_accounts/form', :object => f %>
<% end %>

<p>
<% if @fund_grant %>
<%= link_to 'Back', fund_grant_activity_accounts_path( @fund_grant ) %>
<% end %>
</p>

app/views/activity_accounts/show.html.erb
<p>
  <b>Grant:</b> <%= @activity_account.fund_grant %>
</p>

<p>
  <b>Category:</b> <%= @activity_account.category %>
</p>

<p>
  <b>Comments:</b>
</p>

<%=markdown @activity_account.comments %>

<p>
<% if permitted_to? :edit, @activity_account %>
<%= link_to 'Edit', edit_activity_account_path(@activity_account) %> |
<% end %>
<%= link_to 'Back', fund_grant_activity_accounts_path( @activity_account.fund_grant ) %>
</p>