config/routes.rb
Charon::Application.routes.draw do
  resources :activity_accounts, :except => [ :index, :new, :create ]
  resources :activity_reports, :except => [ :new, :create ]
  resources :addresses, :except => [ :index, :new, :create ]
  resources :agreements do
    resources :approvals, :only => [ :create, :index, :new ]
    resources :fulfillments, :only => [ :index ]
  end
  resources :approvals, :only => [ :show, :destroy ]
  resources :categories
  resources :documents, :only => [ :show ] do
    member do
      get :original
    end
  end
  resources :document_types
  resources :frameworks
  resources :fund_grants, :except => [ :create, :new, :index ] do
    resources :activity_accounts, :only => [ :index, :new, :create ]
    resources :fund_requests, :only => [ :create, :new, :index ]
  end
  resources :fund_editions, :only => [ :destroy ]
  resources :fund_items, :only => [ :destroy ]
  resources :fund_queues, :only => [ :show ] do
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :duplicate, :reviews_report
      end
    end
  end
  resources :fund_request_types
  resources :fund_requests, :except => [ :create, :new ] do
    member do
      get :reject, :documents_report
      put :do_reject, :submit, :withdraw, :reconsider
    end
    resources :approvals, :only => [ :create, :destroy, :index, :new ]
    resources :fund_items, :except => [ :destroy ]
  end
  resources :fund_sources, :except => [ :create, :new ] do
    resources :fund_grants, :only => [ :index ] do
      collection do
        get :released_report
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :unqueued
      end
    end
    resources :fund_tier_assignments, :only => [ :index, :new, :create ]
    resources :organizations, :only => [] do
      collection do
        get :untiered
      end
    end
  end
  resources :fund_tier_assignments, :only => [ :update, :destroy ]
  resources :inventory_items, :except => [ :new, :create ] do
      collection do
        get :retired, :active
      end
  end
  resources :local_event_expenses, :only => [ :index ]
  resources :memberships, :except => [ :create, :new ]
  resources :nodes, :except => [ :index, :create, :new ]
  resources :organizations do
    member do
      get :dashboard
    end
    resources :activity_accounts, :only => [ :index ]
    resources :activity_reports, :only => [ :index, :new, :create ] do
      collection do
        get :past, :current, :future
      end
    end
    resources :fulfillments, :only => [ :index ]
    resources :fund_grants, :only => [ :create, :new, :index ] do
      collection do
        get :closed, :open
      end
    end
    resources :fund_requests, :only => [ :index ] do
      collection do
        get :active, :duplicate, :inactive
      end
    end
    resources :fund_sources, :only => [ :create, :new, :index ]
    resources :inventory_items, :only => [ :index, :new, :create ] do
      collection do
        get :retired, :active
      end
    end
    resources :memberships, :only => [ :create, :new, :index ] do
      collection do
        get :active
      end
    end
    resources :registrations, :only => [ :index ]
    resources :university_accounts, :only => [ :new, :create, :index ]
  end
  resources :registration_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :registrations, :only => [ :index, :show ] do
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
    resources :organizations, :only => [ :new, :create ]
  end
  resources :registration_terms do
    resources :registrations, :only => [ :index, :show ]
  end
  resources :roles
  resources :structures do
    resources :nodes, :only => [ :index, :create, :new ]
  end
  resources :university_accounts, :except => [ :new, :create ] do
    collection do
      get :activate
      put :do_activate
    end
  end
  resources :user_status_criterions do
    resources :fulfillments, :only => [:index]
  end
  resources :users do
    collection do
      get :admin, :staff
    end
    resources :addresses, :only => [ :index, :new, :create ]
    resources :approvals, :only => [ :index ]
    resources :fulfillments, :only => [ :index ]
    resources :memberships, :only => [ :index, :new, :create ] do
      collection do
        get :active
      end
    end
  end

  resource :user_session

  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'profile', :to => 'users#profile', :as => 'profile'

  root :to => 'users#profile'
end

app/models/framework.rb
class Framework < ActiveRecord::Base
  cattr_writer :skip_update_frameworks
  attr_accessible :name, :requirements_attributes, :approvers_attributes

  has_many :approvers, inverse_of: :framework
  has_many :requirements, inverse_of: :framework
  has_many :fund_sources, inverse_of: :framework
  has_many :submission_fund_sources, inverse_of: :submission_framework,
    class_name: 'FundSource', foreign_key: :submission_framework_id
  has_many :requirement_roles, through: :requirements, source: :role,
    uniq: true
  has_and_belongs_to_many :memberships

  has_many :users, through: :memberships
  has_many :organizations, through: :memberships

  validates :name, presence: true, uniqueness: true

  accepts_nested_attributes_for :requirements, allow_destroy: true
  accepts_nested_attributes_for :approvers, allow_destroy: true

  scope :ordered, order { name }
  # Find all fulfillables the membership fulfills
  scope :fulfilled_by, lambda { |membership|
    where { |f|
      f.id.not_in( Requirement.unfulfilled_by( membership ).select { framework_id } )
    }
  }
  scope :fulfilled_for_memberships, lambda { |memberships_scope|
    Framework.joins { memberships }.where { |f| f.memberships.id.in(
      memberships_scope.scoped.select { id } ) }.uniq
  }
  scope :unfulfilled_for_memberships, lambda { |memberships_scope|
    Framework.where { |f| f.id.not_in( memberships_scope.
      joins { frameworks }.select { frameworks.id } ) }.uniq
  }

  after_save :update_memberships

  def update_memberships
    self.membership_ids = Membership.active.fulfill( self ).value_of(:id)
  end

  def to_s; name; end

  # Disables update_frameworks for memberships within block
  # * this is useful for bulk operations where frameworks can be updated
  #   in a single action at the end
  def self.skip_update_frameworks(&block)
    return @@skip_update_frameworks if block.blank?
    old = skip_update_frameworks
    self.skip_update_frameworks = true
    result = yield
    self.skip_update_frameworks = old
    result
  end

end

app/controllers/frameworks_controller.rb
class FrameworksController < ApplicationController
  before_filter :require_user
  before_filter :initialize_context
  before_filter :initialize_index, :only => [ :index ]
  before_filter :new_framework_from_params, :only => [ :new, :create ]
  filter_access_to :show, :new, :create, :destroy, :edit, :update, :attribute_check => true

  # GET /frameworks
  # GET /frameworks.xml
  def index
    @frameworks = @frameworks.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @frameworks }
    end
  end

  # GET /frameworks/1
  # GET /frameworks/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @framework }
    end
  end

  # GET /frameworks/new
  # GET /frameworks/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @framework }
    end
  end

  # GET /frameworks/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
    end
  end

  # POST /frameworks
  # POST /frameworks.xml
  def create
    respond_to do |format|
      if @framework.save
        flash[:notice] = 'Framework was successfully created.'
        format.html { redirect_to(@framework) }
        format.xml  { render :xml => @framework, :status => :created, :location => @framework }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @framework.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /frameworks/1
  # PUT /frameworks/1.xml
  def update
    respond_to do |format|
      if @framework.update_attributes(params[:framework])
        flash[:notice] = 'Framework was successfully updated.'
        format.html { redirect_to(@framework) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @framework.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /frameworks/1
  # DELETE /frameworks/1.xml
  def destroy
    @framework.destroy

    respond_to do |format|
      format.html { redirect_to(frameworks_url) }
      format.xml  { head :ok }
    end
  end

  def initialize_context
    @framework = Framework.find params[:id] if params[:id]
    add_breadcrumb 'Frameworks', frameworks_path
  end

  def initialize_index
    @frameworks = Framework.scoped.ordered
  end

  def new_framework_from_params
    @framework = Framework.new( params[:framework] )
  end
end

app/helpers/frameworks_helper.rb
module FrameworksHelper
end

app/views/frameworks/_form.html.erb
  <%= render "shared/error_messages", target: form.object %>
  <%= form.inputs do %>
    <%= form.input :name %>
  <% end %>

  <%= form.inputs for: :requirements, name: 'requirements' do |subform| %>
    <%= render partial: 'requirements/requirement_fields', locals: { f: subform } %>
  <% end %>

  <div class='links'>
    <p>
      <%= link_to_add_association 'add requirement', form, :requirements,
        partial: 'requirements/requirement_fields' %>
    </p>
  </div>

  <%= form.inputs for: :approvers, name: 'Approvers' do |subform| %>
    <%= render partial: 'approvers/approver_fields', locals: { f: subform } %>
  <% end %>

  <div class='links'>
    <p>
      <%= link_to_add_association 'add approver', form, :approvers,
        partial: 'approvers/approver_fields' %>
    </p>
  </div>

  <%= form.actions %>

app/views/frameworks/_framework.html.erb
  <%= table_row_tag do %>
    <td><%= framework.name %></td>
    <td><%= link_to 'Show', framework %></td>
    <td><%= link_to( 'Edit', edit_framework_path(framework)
      ) if permitted_to? :edit, framework %></td>
    <td><%= link_to( 'Destroy', framework,
        data: { confirm: 'Are you sure?' }, method: :delete
      ) if permitted_to? :destroy, framework %></td>
  <% end %>

app/views/frameworks/edit.html.erb
<h2>Editing framework</h2>

<%= semantic_form_for(@framework) do |f| %>
  <%= render :partial => 'form', :object => f %>
<% end %>

<p>
<%= link_to 'Show', @framework %> |
<%= link_to 'Back', frameworks_path %>
</p>

app/views/frameworks/index.html.erb
<h2>Listing frameworks</h2>

<table>
<thead>
  <tr>
    <th>Name</th>
  </tr>
</thead>
<tbody>
  <%= render :partial => 'framework', :collection => @frameworks %>
</tbody>
</table>

<br />

<p>
<% if permitted_to? :create, Framework.new -%>
<%= link_to 'New framework', new_framework_path %>
<% end -%>
</p>

app/views/frameworks/new.html.erb
<h2>New framework</h2>

<%= semantic_form_for(@framework) do |f| %>
  <%= render :partial => 'form', :object => f %>
<% end %>

<p>
<%= link_to 'Back', frameworks_path %>
</p>

app/views/frameworks/show.html.erb
<h2><%=h @framework %></h2>

<p>
  <strong>Name:</strong> <%=h @framework.name %>
</p>

<h3>Requirements</h3>

<p>
The following requirements must be met before a membership grants privileges under this framework:
</p>

<%= render :partial => 'requirements/requirements', :object => @framework.requirements %>

<h3>Approvers</h3>

<p>
The following must approve before the request can be submitted (requestor) or released (reviewer):
</p>

<%= render :partial => 'approvers/approvers', :object => @framework.approvers %>

<p>
<% if permitted_to? :edit, @framework -%>
<%= link_to 'Edit', edit_framework_path(@framework) %> |
<% end -%>
<%= link_to 'Back', frameworks_path %>
</p>